### ISSUE TITLE
Admin Login Ressults in 404

### ISSUE THREAD

**Issue by cfmaniac** [cstapetrei/npress#13]
As the Title implies, after doing the setup, migration and start the Admin Panel Login http://localhost:3000/login errors with a 404 Not Found

**Comment by cstapetrei** [comment]
Oops...i'll take a look... it's been so long since i did some work on this pet project... :)

**Comment by cstapetrei** [comment]
> As the Title implies, after doing the setup, migration and start the Admin Panel Login http://localhost:3000/login errors with a 404 Not Found

Just did a commit. Issue should be fixed now. Thanks for the heads up :)
